### ISSUE TITLE
Two or more network interfaces fails after the first

### ISSUE THREAD

**Issue by MarLoe** [richardschneider/net-mdns#12]
When having two or more network interfaces (only tested on MacOS), adding membership to the second will fail with the following exception:

> {System.Net.Sockets.SocketException (0x80004005): Address already in use
  at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, System.Object optionValue) [0x000ee] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net.Sockets/Socket.cs:2461 
  at Makaretu.Dns.MulticastService.FindNetworkInterfaces () [0x0022b] in /Users/ml/Projects/DebugPad/net-mdns/src/MulticastService.cs:271 }
	base: {System.ComponentModel.Win32Exception}
	ErrorCode: 10048
	Message: "Address already in use"
	SocketErrorCode: System.Net.Sockets.SocketError.AddressAlreadyInUse
	Non-public members:

**Comment by richardschneider** [comment]
On windows, I have multiple NICs and am not receiving an errors.  I've updated the [Spike](https://github.com/richardschneider/net-mdns/blob/master/Spike/Program.cs) to generate a little more information.  Could you run it and share the results.

Here's what I see on Windows laptop
```
Multicast DNS spike
discovered NIC 'Npcap Loopback Adapter'
discovered NIC 'Ethernet 2'
discovered NIC 'Wi-Fi'
```

**Comment by MarLoe** [comment]
Yes, I'll do that.

**Comment by richardschneider** [comment]
I'm confused, PR #11 is about removing NICs.  This issue is about having two NICs on a MacOS machine.

**Comment by MarLoe** [comment]
Yeah! I see the confusion.

First I experienced the utun01 issue and made a fix.
Then I experienced the two nic issue. PR #11 catches the exception throw by
`socket.SetSocketOption( SocketOptionLevel.IP, SocketOptionName.AddMembership, mopt);`
which also catches the exception thrown by the utun01 nic.

I then removed one nic and experienced that this was not handled. So I made PR #11.

So in short, PR #11 fixes removal of nic and provides a better handling of errors.

**Comment by MarLoe** [comment]
After writing above comment I came to think about one thing:
> Does the 'utun0' nic not work because it sits as the second nic?

So I tried it out. And to my surprise, the 'utun0' does in fact work if it is the first nic in the list.

That means that the changes made in PR #11 are even more correct than what I first anticipated.

**Comment by MarLoe** [comment]
I can confirm that this is fixed!
