### ISSUE TITLE
Question: Bonjour/ZeroConf support

### ISSUE THREAD

**Issue by MarLoe** [richardschneider/net-mdns#13]
Hi

Can you tell me if I can use this library to "broadcast" a bonjour / zeroconf service?
I know that the service itself needs to be implemented separately.
But the info needs to be broadcasted so clients can "pick it up".

I am using [Bonjour Browser](http://www.tildesoft.com/) to discover existing Bonjour services.

Thank you for any input you can provide,

Martin

**Comment by richardschneider** [comment]
Multicast DNS is based on Bonjour so it should work; see https://tools.ietf.org/html/rfc6762#section-1.

You can use `SendQuery` or `SendAnswer` (see the [docs](https://richardschneider.github.io/net-mdns/api/Makaretu.Dns.MulticastService.html)) to do a "broadcast".  Also take a look at the [readme](https://github.com/richardschneider/net-mdns#broadcasting).

**Comment by MarLoe** [comment]
Thank you! I'll take a look at that. 👍

**Comment by richardschneider** [comment]
Currently, only RFC 6762 - Multicast DNS is supported,  Bonjour also requires RFC 6763 - DNS-Based Service Discovery (DNS-SD).

I'm in the process of adding DNS-SD, so hold off for a few days.

**Comment by MarLoe** [comment]
Wow! Thanks! Really looking forward to that :)

**Comment by richardschneider** [comment]
Could you test this on a Mac with by running the `spike` and then using Bonjour Browser.  You should see the _xservice an the _yservice.

I ran [ZeroConf Browser](https://play.google.com/store/apps/details?id=com.melloware.zeroconf&hl=en) on my Android Phone and it saw the `spike` services on my windows laptop!.

**Comment by richardschneider** [comment]
![screenshot_20180709-155032](https://user-images.githubusercontent.com/631061/42429952-4e498bc0-8390-11e8-9485-52ee58936be9.png)

**Comment by MarLoe** [comment]
Hi @richardschneider 

It works like a charm 🥇 
![image](https://user-images.githubusercontent.com/1921282/42437864-9dd8898e-835e-11e8-8226-117185fb12ee.png)

Also the changed you made to the code avoiding using AddMembership runs smoothly on MacOS as well.
Well done!

I have two small comments:
* It would be nice for an easier way to add to the text record strings (also without accidentally removing "txtvers=1").
* In ServiceProfile line 66 you new up a MulticastService to get addresses. An injection pattern like the one you use in ServiceDiscovery would be better I think. Suggestion: Could ServiceDiscovery expose a "CreateService" method taking the parameters instanceName, serviceName, port, addresses and then return a ServiceProfile (and perhaps even making the ServiceProfile constructor internal).

**Comment by richardschneider** [comment]
> It would be nice for an easier way to add to the text record strings (also without accidentally removing "txtvers=1")

This looks pretty easy
```
var service = new ServiceProfile("x", "_sdtest._udp", 1024);
var txt = service.Resources.OfType<TXTRecord>().First();
txt.Strings.AddRange(new [] { "a=1", "b=2" });
```

What suggestions do you have?

**Comment by MarLoe** [comment]
If you know what it is all about, it is easy. That is the exact same line I came up with.
But since you are adding the TXTRecord "behind the scene", people might not know it is there or where to look for it.

So I was thinking in the lines of:
`
var service = new ServiceProfile("x", "_sdtest._udp", 1024);
service.addText(string key, string value); // then do what you do behind the scene...
`

Anyway, this is just a suggestion :)

**Comment by richardschneider** [comment]
Good thoughts, Will define `AddText`.

Also, reverted `GetIPAddresses` and `GetNetworkInterfaces`  to static. So,  ServiceProfile line 66 now reads better.

**Comment by MarLoe** [comment]
Nice 😃

**Comment by richardschneider** [comment]
Should you now close this issue?  Or is there more to do?

**Thanks** for all the input and time you have spent on this project!!!

**Comment by richardschneider** [comment]
All these changes are now in v0.9.0 and published on NuGet.

**Comment by MarLoe** [comment]
The input and time is my pleasure - thanks for letting me contribute.

It seems to work as expected. I will now continue with my other project that needs this feature ;)

I'll keep in touch.
