### ISSUE TITLE
Can't discover any device

### ISSUE THREAD

**Issue by a13u** [richardschneider/net-mdns#20]
I tried to use this library, however I am unable to find any device. Neither the local service nor my printer are visible. What I am doing wrong? (I am using VS2017 and downloaded net-mdns via nuget as well as it's dependencies...). The code you see bellow is the modified test code.
Thank you!

        public static void Main(string[] args)
        {
            var service = new ServiceProfile("x", "_sdtest-2._tcp", 1024);
            var mdns = new MulticastService();
            var sd = new ServiceDiscovery(mdns);

            mdns.NetworkInterfaceDiscovered += (s, e) =>
            {
                Console.WriteLine("found" + s + e);
                sd.QueryAllServices();
            };

            sd.ServiceDiscovered += (s, serviceName) =>
            {
                Console.WriteLine("found" + s + serviceName);
            };
            try
            {
                sd.Advertise(service);
                mdns.Start();
                Console.ReadKey();
            }
            finally
            {
                sd.Dispose();
                mdns.Stop();
            }            
        }

    }

**Comment by a13u** [comment]
I tried a further test: I added my phone to the network where I can discover the printer but not the published service...
I also tried to turn off my firewalls as well my anti-virus app without any success...

**Comment by richardschneider** [comment]
@a13u Sorry that things are not working out.  Can you tell me what OS your are using?

**Comment by a13u** [comment]
no problem ;)
I just want to find out what is happening....
I am using Windows 10

**Comment by a13u** [comment]
In my Windows Printers and Device-Manager I can see the printer - I guess it discovers it with noconfnetwork

**Comment by richardschneider** [comment]
I've tidied up you code, so that console output is readable.  Also, see the [spike](https://github.com/richardschneider/net-mdns/tree/master/Spike) that I wrote to test things out.  

```
        public static void Main(string[] args)
        {
            var service = new ServiceProfile("x", "_sdtest-2._tcp", 1024);
            var mdns = new MulticastService();
            var sd = new ServiceDiscovery(mdns);

            mdns.NetworkInterfaceDiscovered += (s, e) =>
            {
                foreach (var nic in e.NetworkInterfaces)
                {
                    Console.WriteLine($"discovered NIC '{nic.Name}'");
                }
                sd.QueryAllServices();
            };

            sd.ServiceDiscovered += (s, serviceName) =>
            {
                Console.WriteLine("found " + serviceName);
            };
            try
            {
                sd.Advertise(service);
                mdns.Start();
                Console.ReadKey();
            }
            finally
            {
                sd.Dispose();
                mdns.Stop();
            }
        }
```

**Comment by richardschneider** [comment]
Can you show me the output from the above code or from running the spike.

**Comment by a13u** [comment]
I get nothing....
The spike project returns the following

```
Multicast DNS spike
IP address fe80::a4bf:df55:XXXXX
IP address 10.0.0.9
21.07.2018 16:45:25 [DEBUG] Makaretu.Dns.MulticastService - Found nic 'WLAN'.
discovered NIC 'WLAN'
got a query for _homekit._tcp.local PTR, _sleep-proxy._udp.local PTR
21.07.2018 16:46:09 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _homekit._tcp.local PTR
got a query for _homekit._tcp.local PTR, _sleep-proxy._udp.local PTR
21.07.2018 16:46:10 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _homekit._tcp.local PTR
got a query for _homekit._tcp.local PTR, _sleep-proxy._udp.local PTR
21.07.2018 16:46:13 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _homekit._tcp.local PTR
got a query for _homekit._tcp.local PTR, _sleep-proxy._udp.local PTR
21.07.2018 16:46:22 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _homekit._tcp.local PTR
got a query for _http._tcp.local PTR
21.07.2018 16:46:23 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _http._tcp.local PTR
got a query for _http._tcp.local PTR
21.07.2018 16:46:24 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _http._tcp.local PTR
got a query for _http._tcp.local PTR
21.07.2018 16:46:27 [DEBUG] Makaretu.Dns.ServiceDiscovery - got query for _http._tcp.local PTR
```

**Comment by richardschneider** [comment]
Please note that the above is only discovering services available on the local network NOT the devices.

Make this change to ask for all devices (service instances) of a service
```
sd.ServiceDiscovered += (s, serviceName) =>
 {
       Console.WriteLine("found " + serviceName);
      mdns.SendQuery(serviceName, type: DnsType.PTR);
 };

**Comment by richardschneider** [comment]
I have not yet written a generic ServiceInstanceDiscovery (device discovery) method yet.  The above code will ask for all devices with the services names and you can see the answer in the debug logs.

However to process the information you need to drop down to [mdns.AnswerReceived](https://richardschneider.github.io/net-mdns/api/Makaretu.Dns.MulticastService.html#events)

**Comment by richardschneider** [comment]
I'll add some device discovery into the spike.  However its 03:00 my time and I'm goinf to bed.  Talk to later and BTW thanks for the interest in the project.

**Comment by a13u** [comment]
I added sd.QueryAllServices(); to "mdns.NetworkInterfaceDiscovered += (s, e) =>.." in Spike
Now I find at least my local services ;)

**Comment by a13u** [comment]
Thank you for your support

**Comment by richardschneider** [comment]
`QueryAllServices` does not need to  be called continuously because new services will advertise themselves.

To get the service instance host name.  You need to send a query for its SRV record then query for A/AAAA records.

**Comment by richardschneider** [comment]
An example **browser** is now at https://github.com/richardschneider/net-mdns/blob/master/Browser/Program.cs

Hope it helps.
