### ISSUE TITLE
MDNS does not start in UWP app

### ISSUE THREAD

**Issue by queequac** [richardschneider/net-mdns#21]
I was always looking for a MDNS library that can query and announce services at the same time. Seems your library could be the perfect match. :)

While I got it running within .NET 4.6.1, it seems no to work for a Windows 10 UWP app. 
I took your browser sample from here: https://github.com/richardschneider/net-mdns/blob/master/Browser/Program.cs

I have set all neccessary capabilities for private network and so on, and I split the code into one half setting up handlers and starting the service and another half that stops and disposes.

But unfortunately it seems the multicast service does not even start.
First I realized I never get the NetworkInterfaceDiscovered event... so I added another button for testing purposes which shall do the query anyway - but this one always throws an exception that mdns got not started. So I am wondering what could block `mdns.start();` internally from starting?

Can anyone confirm this for UWP?

**Comment by richardschneider** [comment]
Did you make any changes to support .NET 4.6.1?  If so can you make a PR.

I have no experience with Windows 10 UWP.  Please point me to the repo that has the App for UWP.  I'll be happy to debug it.

**Comment by richardschneider** [comment]
After some investigation, it appears that `System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces` is throwing  a NotImplementedException; see this [issue](https://github.com/dotnet/corefx/issues/9675).

**Comment by richardschneider** [comment]
You need to set the UWP `min version target` to Build 16299; this uses .Net Standard 2 and implements `GetAllNetworkInterfaces`.

![target](https://user-images.githubusercontent.com/631061/43999077-c27045b0-9e58-11e8-8404-93e7bcbe361d.png)

**Comment by queequac** [comment]
Ah, thanks for investigating!
Unfortunately my app is out in the wild and last version of Windows 10 Mobile does not support the FCU update (it does, but not on API level). That was yet another reason why I wanted to switch from Zeroconf, which also supports only .NET Standard 2 starting with their v3 release.

Do you consider supporting 1.4? Your current readme.md and the library's dependency graph do otherwise just "trick" people like me. :)

**Comment by richardschneider** [comment]
.Net Standard 1.4 is supported and is tested against CoreApp 1.1 See the Appveyor logs or try it on your machine with `dotnet test -c Release test`. 

For 1.4 the package "System.Net.NetworkInformation" Version="4.3.0" is included. It appears that UWP does not include this package.  

I'm sorry, bit I'm not interested in supporting old versions of UWP.  However, if you can figure out how to get old UWP to use new `NetworkInformation` then I am glad to accept a PR.
