### ISSUE TITLE
Ability to restrict service querying to specific network interface.

### ISSUE THREAD

**Issue by michaelosthege** [richardschneider/net-mdns#29]
~~Just like the mDNS advertising can be restricted to specific IPAddresses, it would consistent to do the same for queries.~~

This is a feature request for the ability to restrict both service advertising and service discovery to a set of network interfaces.

### Motivation
The situation in my case is a computer that is connected to two networks.  I ran into a lot of trouble, because the current implementation attempts to use all network interfaces simultaneously:
- no exception is raised when the `UdpClient` can not be created on a particular interface
- there is no way to restrict activity to a particular interface
- a firewall configuration can prevent the program from opening a port on some interfaces

### Proposed solution
Support for restricting activity to a specific network interface could be implemented via a `NetworkInterfaces[]` parameter to the constructor of the `MulticastService`.

**Comment by richardschneider** [comment]
Sorry for the late reply! I am very confused by your issue.

> Just like the mDNS advertising can be restricted to specific IPAddresses, it would consistent to do the same for queries.

Not sure about this.  How is it restricted to a specific IPAddress?

> When the user asks for an mDNS query on a specific network interface, an exception should be raised in such cases.

A query is sent on all network interfaces.  There is no way to use a specific interface.

**Comment by richardschneider** [comment]
I do not see a need to restrict Service Discovery to a specific interfaces.  mDNS is all about zero configuration.

As for advertising, the ServiceProfile can specify which addresses it is listening on.

**Comment by michaelosthege** [comment]
Replying to your last comment on #30 ...

> 
> 
> @michaelosthege thanks for the update.
> 
> As you may guess, I'm a solo developer and **don't deal** with "corporate firewalls." However, I would expect a firewall to simply not forward the datagram on a restricted interface/port; which should not cause an issue with creating a `UdpClient`.
> 
> Can you open a new issue that shows the actual exception (and stack trace) you are getting?
> 
> As always, I'm happy to get a PR.

I'm working on PR https://github.com/richardschneider/net-mdns/pull/32 right now. When I was trying to debug earlier, I did some things wrong.

The problem now is, that I don't get any exception at all. As I described more detailed in the thread on the PR, there is zero activity on the local network interface without specifying it explicitly.
