### ISSUE TITLE
Invalid clearing of additional records

### ISSUE THREAD

**Issue by eshvatskyi** [richardschneider/net-mdns#34]
https://github.com/richardschneider/net-mdns/blob/cb3d0bd58da1b77a7e65f059a1f457bdfa780753/src/ServiceDiscovery.cs#L205

Should be

               // Many bonjour browsers don't like DNS-SD response
                // with additional records.
                if (response.Answers.Any(a => a.Name == ServiceName))
                {
                   if (AnswersContainsAdditionalRecords)
                   {
                       response.Answers.AddRange(response.AdditionalRecords);
                   }
                    response.AdditionalRecords.Clear();
                }

**Comment by richardschneider** [comment]
I agree, but the `if (AnswersContainsAddditionalRecords)` should be before the DNS-SD test.

Would you like to create a PR.  This way you will get credit as a contributor!

**Comment by eshvatskyi** [comment]
I do, ) I have 1 optimization for DNS
and fix for mdns (using with multiple NIC)

**Comment by eshvatskyi** [comment]
Please let me know how I could create a PR

**Comment by richardschneider** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by eshvatskyi** [comment]
Lol ))  I meant I dont have permissions ) to do this

**Comment by eshvatskyi** [comment]
Created 2 PRs, please check. not perfect ) but tested on multy Nics works perfect on windows 10 host.
Later will test on linux alpine

**Comment by richardschneider** [comment]
Does #40 resolve this issue?
