### ISSUE TITLE
Not working for multi active NICs

### ISSUE THREAD

**Issue by eshvatskyi** [richardschneider/net-mdns#37]
https://stackoverflow.com/questions/6976526/udp-multicasting-with-multiple-nics-only-works-when-one-interface-is-active

1. it's bonded only to 1 from 3 available and receiving messages only for it.
2. No need to recreate LISTENER all the time, since there is used IPAddress.ANY. I'm using TCPListener in a project with the same binding. All works without re-creating, when disabling one NIC it's just become unavailable for a subnet, and when enabling it back - it's back online.

**Comment by richardschneider** [comment]
Does #40 resolve this?
