### ISSUE TITLE
Example: Updating a record

### ISSUE THREAD

**Issue by Visic** [richardschneider/net-mdns#53]
I need to be able to update records after they are being advertised, but cannot figure out how. This seems like it would be a fairly common requirement, so an example would go a long ways.

**Comment by richardschneider** [comment]
Updating MDNS is NOT fairly common.  Could you explain what you want to update?

**Comment by Visic** [comment]
I could do it one of two ways:
1. Stop the current service and restarted a new one (we would need the Goodbye message on cleanup)
2. Update the service "instance name" and CNAME record name

Unrelated, but for what it's worth, this library is a pleasure to work with. Additionally, it's the best MDNS library I have used across half a dozen different programming languages.

**Comment by richardschneider** [comment]
Stopping a service is discussed in issue #47;  @cerna any progress on the issue?

All the resource records for a service are in `ServiceDiscovery.NameServer.Catalog`.  See https://richardschneider.github.io/net-dns/articles/rr.html for supported resource records.

**Comment by richardschneider** [comment]
@Visic its been 3+ weeks since you last comment.  This issue will be closed next week unless I hear from you.

**Comment by Visic** [comment]
@richardschneider I am still interested in this functionality, I haven't had time to dig into making the changes myself, but as soon as it is ready I will be using it in production.

**Comment by percramer** [comment]
I would also like to know how to update. I would like to send status info about my service in the properties
