### ISSUE TITLE
Why is the question/answer type not checked

### ISSUE THREAD

**Issue by Salazander** [richardschneider/net-mdns#70]
Is there a good reason why the response type is not compared to the question type? I am currently facing the issue where I get AAAA records instead of A records.

https://github.com/richardschneider/net-mdns/blob/879f86f17db8c87bf3d6cd39a1f6c8f29905ac01/src/MulticastService.cs#L329

**Comment by richardschneider** [comment]
Sounds like a reasonable change.  Please submit a PR.

Remember that a question can have `DnsType.Any`.
