### ISSUE TITLE
Advertise apparently not working

### ISSUE THREAD

**Issue by AzeExMachina** [richardschneider/net-mdns#71]
Hi, I'm trying to use your code to publish an application on my local network. I've tested the browser and advertiser programs but there's maybe something I'm not understanding. The browser program works fine, I can see all the services and whatnot running on my network. I've also made a simple node js script to publish something using zeroconf and as soon as it gets published I can see it with the browser. 
My issue lies with the advertiser, do I need bonjour installed? I've tried your program but I can't see anything when also running the browser, is it because I don't have bonjour installed?

Thanks in advance

**Comment by richardschneider** [comment]
No you do not need bonjour installed.  Can you please provide an example and a description of the problems.

**Comment by AzeExMachina** [comment]
Sure thing, I've used these two scripts
- https://github.com/richardschneider/net-mdns/blob/master/Spike/Program.cs
- https://github.com/richardschneider/net-mdns/blob/master/Browser/Program.cs

I've put those in two different console application, running in visual studio 2019, targeting .NET Framework 4.7.2, the only things I've commented out are the ones about the logging since I didn't need that. Then I started debugging the browser and I get all the console entries about all the devices up and running on my local network. After that I've started the advertiser program but I get no logs whatsoever about that.

**Comment by AzeExMachina** [comment]
I'm updating this issue saying that the actual problem was caused by having multiple NICs, I had docker and hyper V both creating a network interface, calling advertise and mdns with only the address of the physical one works.

**Comment by twofingerrightclick** [comment]
Sounds like I am having a similar issue. Cannot see the service my app advertises on my LAN, but also cannot browse the LAN. I can only browse and "see" the services on my machine, so I can see the one my app is advertising, but I have lots of googlecast_tcp services on my network, they dont show up though, only stuff running on my machine. I have several interfaces (docker, v-nets... etc), but want to just use the wlan0, or eth0 (I am doing dev on windows, so windows equivalents). I will comment if I figure out the issue. I tried going back a step and running the Spike example program, but it behaves the same as my implementation.  Only advertises on the machine, not the Wi-Fi nic (LAN).

Example interface output from the Spike program:
```
discovered NIC 'Ethernet 2'
discovered NIC 'ZeroTier One - 0'
discovered NIC 'ZeroTier One - 1'
discovered NIC 'Wi-Fi'
```
Also the mdns.QueryReceived event doesn't get fired with anything but `wpad.local A` queries on the ZeroTier virtual interfaces. Other queries on the physical interfaces don't get through.

When I started the app the first time Windows asked me to give it permission to use my WiFi network.

**Comment by twofingerrightclick** [comment]
How do I specify what interface to advertise on? And is that really necessary?

**Comment by AzeExMachina** [comment]
> How do I specify what interface to advertise on? And is that really necessary?

It was a couple of years ago but in my case it was necessary to specify the physical network interface you use for your lan.

I retrieved the address from my physical NIC and then advertise on those
```
var addresses = networkInterface.GetIPProperties().UnicastAddresses.Where(o => o.Address.AddressFamily == AddressFamily.InterNetwork).Select(o => o.Address);
var serviceProfile = new ServiceProfile("name", "_something._tcp", publishPort, addresses);
sd.Advertise(serviceProfile);
```

**Comment by twofingerrightclick** [comment]
@AzeExMachina thanks for replying. I tried explicitly defining the IP of my wifi interface, but no dice. But I did try disabling the vnets and loopback and now I am getting different questions and answers I wasn't seeing before... I think I am getting somewhere.
![image](https://user-images.githubusercontent.com/11265760/173176054-55549efe-fd6a-43bf-9e1e-75ec833bd7d3.png)
