### ISSUE TITLE
Not working on android & iOS (Unity)

### ISSUE THREAD

**Issue by nicwhitts** [richardschneider/net-mdns#73]
Hi,
Iv got the mDNS working within the editor of unity. But once i build and run on android or iOS devices, it doesn't work.

There is no errors or log messages, do you have any idea why this might be happening?

Thanks!

**Comment by richardschneider** [comment]
Android and iOS devices are not supported.  

I think you will need Xamarin Mobile Apps.  I suggest you try to get the unit tests running on the device.

**Comment by dustinkerstein** [comment]
Was just curious. @nicwhitts, did you ever find a solution for Android/iOS + Unity? I know for both iOS and Android you have to declare the correct permissions and specifically on Android you need to acquire a MultiCastLock.

**Comment by nicholaswhittle** [comment]
I did get it kind of working. I used react native, and using a multicast npm package which I think I had to slightly modify for react native support. I packaged unity within react native using npm package react-native-unity-view. 
there is a recent fork with newer unity support too. 

But.. I found the multicast a bit unreliable.
My use case was to connect two devices so I opted for a qr code which I would scan with one device to connect the two.

**Comment by dustinkerstein** [comment]
Interesting. Thanks for the update. I settled on a less sophisticated approach and am doing a head request across all IPs on the network looking for my server that is listening on a particular port + page. Very ugly, but seems to be much more reliable than multicast...
