### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by koliyo** [richardschneider/net-mdns#74]
Is there a reason why .NET Core is not a target platform? The current .NET direction seems very focused on the Core platform, especially for crossplatform environments, eg Linux/Mac. 

I am developing .NET on a Mac and would very much appreciate being able to use the Core target.

**Comment by richardschneider** [comment]
It supports .NET Core by producing a ,NET Standard library,  Linux and Mac platforms are tested in the CI workflow.

**Comment by koliyo** [comment]
Oh nice! Yeah I see now how it works, did some reading. Great job with the library!
