### ISSUE TITLE
"RecentMessages" not thread safe.

### ISSUE THREAD

**Issue by Luai-m** [richardschneider/net-mdns#75]
I get a lot of silent exceptions thrown by the MD5 hash algorithm. You can see these exceptions by either enabling "System.Security.Cryptography.ChryptographicException" in debug exception settings or by adding a handler to `TaskScheduler.UnobservedTaskException`.
It's because the `ComputeHash` is not thread safe. I suggest to not reuse the created `MD5` object and instead create it each time when calculating hash.
So:

`using (HashAlgorithm hasher = MD5.Create())`
`{`
          `return Convert.ToBase64String(hasher.ComputeHash(message));`
`}`

**Comment by richardschneider** [comment]
Thanks for the bug report.  You are correct: MD5 is not thread safe.

Do you want to submit a PR?

**Comment by Luai-m** [comment]
I tried to push a branch, but I don't have access to the repository.

**Comment by richardschneider** [comment]
Read https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by Luai-m** [comment]
Done. When can it be released?

**Comment by richardschneider** [comment]
Fixed in release https://github.com/richardschneider/net-mdns/releases/tag/v0.25.0
